### Get Route API-Gateway - Restricted to only GET Request
GET https://6xtbzore5g.execute-api.us-east-1.amazonaws.com/prod/



### Get Route API-Gateway - Restricted to only GET Request (Proxy=false)
GET https://1sb3esgj81.execute-api.us-east-1.amazonaws.com/prod/cars



### Get Route API-Gateway - Restricted to only GET Request (Proxy=false)
GET https://1sb3esgj81.execute-api.us-east-1.amazonaws.com/prod/trucks